name: minefocus_sns_login_flutter
description: A Flutter plugin for google、facebook、yahoo login
version: 1.0.0
author: cong wang <cong.wang3@pactera.com>
homepage: https://github.com/minefocus/minefocus_sns_login_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: 5.0.5
  flutter_facebook_auth: ^3.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.scsk.minefocus_sns_login_flutter
    pluginClass: MinefocusSnsLoginFlutterPlugin